stages:
  - build
  - test
  - deploy

# --- Build Stage ---
build-job:
  stage: build
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Build stage dependencies installed"

# --- Test Stage ---
unit-test-job:
  stage: test
  image: python:3.10
  services:
    - name: postgres:17
      alias: test_db
  variables:
    POSTGRES_DB: test_heroes
    POSTGRES_USER: test_hero
    POSTGRES_PASSWORD: test_hero
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export DATABASE_URL=postgresql://test_hero:test_hero@test_db:5432/test_heroes
  script:
    - echo "Running unit tests..."
    - pytest -v --maxfail=1 --disable-warnings

lint-test-job:
  stage: test
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install flake8
  script:
    - echo "Running linter..."
    - flake8 app tests

# --- Deploy Stage ---
deploy-job:
  stage: deploy
  script:
    - echo "Deploy stage would deploy application here..."

