stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $DOCKER_HUB_USERNAME/it_school
  VERSION_TAG: 1.0.$CI_PIPELINE_IID

# --- 1. Build Docker image ---
build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    # Логинимся в Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    # Собираем образ с тегом SHA и latest
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:$VERSION_TAG
    # Пушим оба тега
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$VERSION_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - |
      ssh $DEPLOY_USER@$DEPLOY_SERVER "
        export IMAGE_NAME=$IMAGE_NAME &&
        export VERSION_TAG=$VERSION_TAG &&
        cd ~ &&
        docker compose pull web &&
        docker compose up -d web
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
